### ISSUE TITLE
Cannot start Kuzzle 2.10.0: [FATAL] Service "elasticsearch": initialization timeout

### ISSUE THREAD

**Issue by nishit93-hub** [kuzzleio/kuzzle-kubernetes#1]
Hi,
 
**When i try to deploy kuzzle.yaml, i am getting following error:-**

[ℹ] Starting Kuzzle 2.10.0 ...
[✔] Cache initialized
[ℹ] Trying to connect to Elasticsearch...
[X] Cannot start Kuzzle 2.10.0: [FATAL] Service "elasticsearch": initialization timeout
[x] [ERROR] InternalError: [FATAL] Service "elasticsearch": initialization timeout
      [...Kuzzle internal calls deleted...]
>    at /var/app/lib/service/service.js:60:24
       at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:547:31)
       at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:604:18)
       at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:649:10)
       at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:725:18)
       at _drainQueueStep (/var/app/node_modules/bluebird/js/release/async.js:93:12)
       at _drainQueue (/var/app/node_modules/bluebird/js/release/async.js:86:9)
       at Async._drainQueues (/var/app/node_modules/bluebird/js/release/async.js:102:5)
       at Immediate.Async.drainQueues [as _onImmediate] (/var/app/node_modules/bluebird/js/release/async.js:15:14)
       at processImmediate (internal/timers.js:456:21)
       
       
  Please help!

**Comment by Aschen** [comment]
Hi @nishit93-hub ,

Kuzzle cannot start because he cannot connect to Elasticsearch.
You should look into your Elasticsearch container logs to find your problem.

**Comment by nishit93-hub** [comment]
Hi,
I have checked Elasticsearch  container logs, its all clear .Didn't find any wrong there.
Here is the Elasticsearch url **https://elastic.dispatchcargo.com**

Using this in kuzzle env i.e.
kuzzle_services__storageEngine__client__node=https://elastic.dispatchcargo.com

**Comment by Aschen** [comment]
As far as I can see your current ES version is 7.10 (See this ticket https://github.com/kuzzleio/kuzzle/issues/1966) and we do not officially support this version for now. Maybe it's why the service initialization time out.

Can you try to run your application with ES 7.4 and tell me if you still have the issue?
